### ISSUE TITLE
SchemaUrl修正为SchemaUri

### ISSUE THREAD

**Issue by kr9226** [bububa/kwai-marketing-api#28]
model/unit/create_request.go中的SchemaUrl应该是SchemaUri
<img width="1583" alt="image" src="https://user-images.githubusercontent.com/14015070/176585310-33706683-2d05-41f6-ad29-9ee3e8844cdb.png">
[https://developers.e.kuaishou.com/docs?docType=DSP&documentId=1904](url)

**Comment by bububa** [comment]
release v1.3.1
