### ISSUE TITLE
获取素材报表结果返回数据 json失败

### ISSUE THREAD

**Issue by liqkj** [bububa/kwai-marketing-api#29]
![image](https://user-images.githubusercontent.com/29451637/180695032-2627dd52-791b-4983-8e2e-779ea5fa1624.png)
获取素材报表结果返回数据 json失败
![image](https://user-images.githubusercontent.com/29451637/180695071-917b334e-7261-49fc-b720-138034b30b9d.png)

**Comment by liqkj** [comment]
好像是 接口返回参数发生变化了

**Comment by bububa** [comment]
把debug打开，返回结果贴出来我看看
`clt.SetDebug(true)`

**Comment by liqkj** [comment]
![1658813286638](https://user-images.githubusercontent.com/29451637/180930289-ddd7f2fe-3647-4f6d-9df5-7fc684b8bf25.jpg)

**Comment by liqkj** [comment]
这个接口结构体参数 没有写全 
![image](https://user-images.githubusercontent.com/29451637/180930478-7e7d28fb-b84b-460e-a57e-f2a61457c49d.png)

**Comment by bububa** [comment]
这个api好像和别的api都不一样，一般都会返回{code:0,message:"ok",data:{}}，这个A P I结果不标准没有包裹在data里，我想想怎么弄吧，快手实在是太傻逼了

**Comment by liqkj** [comment]
理解，这个接口 他们没有按照标准来

**Comment by liqkj** [comment]
提工单，叫他们改

**Comment by liqkj** [comment]
把返回的数据 结构体参数补全把

**Comment by bububa** [comment]
v1.3.3应该修复了

**Comment by liqkj** [comment]
AdPhotoPlayed10SRatio:       data.AdPhotoPlayed10SRatio,       // 播放10s率
			AdPhotoPlayed2S:             data.AdPhotoPlayed2S,             // 播放2s数
			AdPhotoPlayed2SRatio:        data.AdPhotoPlayed2SRatio,        // 播放2s率
			Play3SRatio:                 data.Play3SRatio,                 // 3s播放率
			Play5SRatio:                 data.Play5SRatio,                 // 5s播放率

这几个参数没有写

**Comment by liqkj** [comment]
不好意思看错了
