### ISSUE TITLE
List 获取广告组信息有部分情况会报错

### ISSUE THREAD

**Issue by 594872799** [bububa/kwai-marketing-api#40]
在Unmarshal成ListResponse的时候会有情况报错，因为返回值中product_id为string类型

`
"{\"total_count\":110,\"details\":[{\"asset_mining\":false,\"ad_type\":0,\"site_type\":0,\"product_image\":null,\"schema_uri\":\"\",\"bid_type\":12,\"package_id\":xxx,\"product_price\":null,\"put_status\":1,\"smart_cover\":false,\"dpa_outer_ids\":[],\"dpa_unit_sub_type\":4,\"u_link\":\"\",\"app_store\":[],\"app_download_type\":0,\"playable_id\":0,\"playable_switch\":0,\"product_id\":\"**这里为字符串**\",\"unit_source\":0,\"schema_id\":\"\",\"app_id\":xxxx,\"campaign_id\":xxx,\"fiction_id\":0,\"ocpx_action_type\":190,\"day_budget\":0,\"use_app_market\":"
`

cannot unmarshal string into Go struct field Unit.details.product_id of type uint64
报错代码路径为：
../github.com/bububa/kwai-marketing-api/api/unit/list.go

**Comment by 594872799** [comment]
应该是大部分情况为null，有小部分配置了productid的补位null，但他是字符串

**Comment by bububa** [comment]
改用了model.Uint64类型，可以unmarshal string->uint64
