### ISSUE TITLE
I saw that in the Kuaishou Cili Engine developer documentation, some APIs have been marked as offline.

### ISSUE THREAD

**Issue by xcrossed** [bububa/kwai-marketing-api#43]
I saw that in the Kuaishou Magnetic Engine developer documentation, some APIs have been marked as offline. Is there any plan to develop support for new APIs, such as obtaining advertising plan information in Intelligent Creation?

<img width="741" alt="image" src="https://github.com/bububa/kwai-marketing-api/assets/998560/3d30d337-3b4d-43a9-8962-0f0891eeaa2f">

https://developers.e.kuaishou.com/docs?docType=DSP&documentId=2261&menuId=2806

**Comment by xcrossed** [comment]
<img width="1129" alt="image" src="https://github.com/bububa/kwai-marketing-api/assets/998560/6b69ac81-b99c-4c1a-bc51-e12daf20442f">

**Comment by bububa** [comment]
Maybe, when I have time. Pull requests are welcome.
