### ISSUE TITLE
1.10.0版本中没有了【获取罗盘绑定广告主列表】接口

### ISSUE THREAD

**Issue by 594872799** [bububa/kwai-marketing-api#51]
v1.4.9中是有的，为什么1.10.0中就没有了
![image](https://github.com/user-attachments/assets/ea0a3311-7a2d-442d-9012-bf2668666fae)

官网地址：https://developers.e.kuaishou.com/docs?docType=DSP&documentId=2615&menuId=3339

**Comment by bububa** [comment]
有啊， github.com/bububa/kwai-marketing-api/api/adcompass

**Comment by 594872799** [comment]
![image](https://github.com/user-attachments/assets/63068425-f3d6-4468-a4b2-43683d0238fd)
啊？现在仓库里面是有，但是releases 1.10.0 没有吧？

**Comment by 594872799** [comment]
我全局搜路径都搜不到

**Comment by 594872799** [comment]
我看看是不是我golang版本的问题
